### ISSUE TITLE
Training procedure

### ISSUE THREAD

**Issue by zxnga** [RoyElkabetz/citylearn_multi_agent_smartgrid#2]
Hello all,

First thanks a lot for such inspiring and well documented work.
I'd like to train your solution on another dataset, could you please give me more details on the training procedure so that I can use your implementation ?

Thanks a lot !

**Comment by galNess** [comment]
Hi Theo,

In the `net_consumption_mlp` folder, you'll find everything MLP training-related. 
`main_mlp.py` gets the training done and stores the top-performing weights in a `.pt` file.

`sequal_prediction` is a boolean which, when turned on, the model spits out predictions one step at a time and uses its own predictions to make the next one, doing this 23 times for the complete forecast (like in RNNs and LSTMs). If it's off (default), it goes for TDNN-style prediction with 24-to-24 timesteps.

Also, the model uses a specialized dataset we designed, structured with stacks of 1+7+7 features. You’ll find more info about this in documentation inside `data_preprocessing.py`.

`eval_exp_mlp.py` helps in tweaking a few hyperparameters, and `mlp_predictor.py` is an easy-to-use script that fits right into the inferencing process.


Best,
Gal

**Comment by galNess** [comment]
Hi Theo,

In the `net_consumption_mlp` folder, you'll find everything MLP training-related. 
`main_mlp.py` gets the training done and stores the top-performing weights in a `.pt` file.

`sequal_prediction` is a boolean which, when turned on, the model spits out predictions one step at a time and uses its own predictions to make the next one, doing this 23 times for the complete forecast (like in RNNs and LSTMs). If it's off (default), it goes for TDNN-style prediction with 24-to-24 timesteps.

Also, the model uses a specialized dataset we designed, structured with stacks of 1+7+7 features. You’ll find more info about this in documentation inside `data_preprocessing.py`.

`eval_exp_mlp.py` helps in tweaking a few hyperparameters, and `mlp_predictor.py` is an easy-to-use script that fits right into the inferencing process.


Best,
Gal

**Comment by zxnga** [comment]
Hello again Gal,

Thank you very much for all the informations you provided, it's really helpful !

Regards,
Theo
